env:
  es6: true
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  no-console: 
    - 0
  indent:
    - error
    - tab
  linebreak-style:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-vars: ["error"]
